#!/usr/bin/env python3
"""
Export prototype Quản Lý Hợp Đồng thành package HTML độc lập cho PO review.

Không sửa Prototype gốc. Chạy:

    python scripts/export_contract_review.py

Output:
    export/contract-review/
    export/contract-review.zip
"""
from __future__ import annotations

import json
import re
import shutil
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PROTO = ROOT / "Prototype"
OUT_DIR = ROOT / "export" / "contract-review"
ZIP_PATH = ROOT / "export" / "contract-review.zip"

CSS_FILES = [
    "theme.css",
    "layout.css",
    "button.css",
    "form.css",
    "table.css",
    "modal.css",
    "sidebar.css",
    "header.css",
    "utility.css",
    "display.css",
    "contract.css",
]

COMPONENTS = [
    "Button", "Input", "Textarea", "Select", "MultiSelect", "DatePicker",
    "Checkbox", "Radio", "Switch", "Tag", "Badge", "Avatar",
    "Table", "Pagination", "Card", "Breadcrumb", "SearchBox", "FilterPanel",
    "EmptyState", "Loading", "Spinner", "Modal", "Dialog", "Toast", "Notification",
    "Tabs", "Collapse", "Menu", "Sidebar", "Header", "Tree", "TreeSelect", "Tooltip", "DonutChart",
]

MENU_ITEMS = [
    {
        "label": "Quản Lý Hợp Đồng",
        "icon": "📄",
        "expanded": True,
        "children": [
            {"label": "Danh sách hợp đồng", "route": "/contract/list"},
        ],
    }
]

README = """# Quản Lý Hợp Đồng – Prototype

## Cách mở

1. Giải nén file ZIP.
2. Mở file `index.html`.
3. Prototype sẽ chạy trên trình duyệt.

## Chức năng có thể review

- Danh sách hợp đồng
- Filter
- Tìm kiếm
- Tạo mới
- Chỉnh sửa
- Xem chi tiết
- In hợp đồng
- Duyệt hợp đồng
- Xóa hợp đồng
- Upload file PDF

## Lưu ý

Đây là prototype dùng mock data.
Không kết nối hệ thống thật.
"""

APP_JS = r"""/**
 * Contract review bootstrap — standalone, no fetch / no localhost.
 * Generated by scripts/export_contract_review.py
 */
(function () {
  'use strict';

  function ensureContractHash() {
    var hash = location.hash || '';
    var path = hash.replace(/^#/, '').split('?')[0];
    if (!path || path === '/' || path === '/dashboard') {
      history.replaceState({ path: '/contract/list' }, '', '#/contract/list');
    }
  }

  function initGlobalEvents() {
    document.addEventListener('click', function (e) {
      var toggle = e.target.closest('.dms-menu__toggle');
      if (toggle) {
        toggle.closest('.dms-menu__item').classList.toggle('is-expanded');
      }

      if (e.target.closest('[data-action="sidebar-toggle"]')) {
        document.getElementById('dms-sidebar').classList.toggle('is-collapsed');
      }

      var tab = e.target.closest('.dms-tabs__tab');
      if (tab) {
        var tabs = tab.closest('.dms-tabs');
        tabs.querySelectorAll('.dms-tabs__tab').forEach(function (t) { t.classList.remove('is-active'); });
        tabs.querySelectorAll('.dms-tabs__panel').forEach(function (p) { p.classList.add('is-hidden'); });
        tab.classList.add('is-active');
        var panel = tabs.querySelector('[data-panel="' + tab.dataset.tab + '"]');
        if (panel) panel.classList.remove('is-hidden');
      }

      var collapseHeader = e.target.closest('.dms-collapse__header');
      if (collapseHeader) {
        collapseHeader.closest('.dms-collapse__item').classList.toggle('is-open');
      }
    });
  }

  function initApp() {
    ensureContractHash();

    document.getElementById('app').innerHTML = DMS.render('MainLayout', {
      menuItems: window.__CONTRACT_MENU_ITEMS,
      role: 'Admin',
      userName: 'Vũ BA'
    });

    DMSRouter.register('/contract', window.renderContractList);
    DMSRouter.register('/contract/list', window.renderContractList);
    DMSRouter.register('/dashboard', function () {
      DMSRouter.navigate('/contract/list', true);
      return '';
    });
    DMSRouter.register('*', function () {
      DMSRouter.navigate('/contract/list', true);
      return '';
    });

    DMSRouter.init({ contentEl: document.getElementById('dms-content') });
    initGlobalEvents();
    if (DMS.get('Tooltip') && typeof DMS.get('Tooltip').init === 'function') {
      DMS.get('Tooltip').init();
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initApp);
  } else {
    initApp();
  }
})();
"""


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def copy_file(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)


def patch_contract_shared(src: Path, dest: Path) -> None:
    text = src.read_text(encoding="utf-8")
    old = """  async function loadStore() {
    if (window.__contractStore) return window.__contractStore;
    const res = await fetch('data/contract.json?v=20260818-contract');
    if (!res.ok) throw new Error('Không tải được dữ liệu hợp đồng');
    window.__contractStore = await res.json();
    return window.__contractStore;
  }"""
    new = """  async function loadStore() {
    if (window.__contractStore) return window.__contractStore;
    if (window.__CONTRACT_SEED) {
      window.__contractStore = JSON.parse(JSON.stringify(window.__CONTRACT_SEED));
      return window.__contractStore;
    }
    throw new Error('Không tải được dữ liệu hợp đồng');
  }"""
    if old not in text:
        raise RuntimeError("Không tìm thấy loadStore() trong contract-shared.js — kiểm tra source trước khi export.")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text.replace(old, new, 1), encoding="utf-8")


def patch_router_default(src: Path, dest: Path) -> None:
    text = src.read_text(encoding="utf-8")
    text = text.replace("return path || '/dashboard';", "return path || '/contract/list';")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8")


def build_index_html(script_tags: list[str]) -> str:
    css_links = "\n".join(
        f'  <link rel="stylesheet" href="assets/css/{name}" />' for name in CSS_FILES
    )
    scripts = "\n".join(f'  <script src="{src}"></script>' for src in script_tags)
    return f"""<!DOCTYPE html>
<html lang="vi">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>eco dms – Quản Lý Hợp Đồng</title>
  <link rel="icon" type="image/svg+xml" href="assets/icons/favicon.svg" />
{css_links}
</head>
<body>
  <div id="app">
    <div class="dms-loading">
      <div class="dms-spinner dms-spinner--lg"></div>
      <p>Đang khởi tạo Prototype...</p>
    </div>
  </div>
{scripts}
</body>
</html>
"""


def zip_dir(src_dir: Path, zip_path: Path) -> None:
    if zip_path.exists():
        zip_path.unlink()
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file in sorted(src_dir.rglob("*")):
            if file.is_file():
                zf.write(file, file.relative_to(src_dir.parent))


def main() -> None:
    if not PROTO.exists():
        raise SystemExit(f"Không tìm thấy Prototype: {PROTO}")

    if OUT_DIR.exists():
        shutil.rmtree(OUT_DIR)
    OUT_DIR.mkdir(parents=True)

    css_dir = OUT_DIR / "assets" / "css"
    js_dir = OUT_DIR / "assets" / "js"
    icons_dir = OUT_DIR / "assets" / "icons"
    images_dir = OUT_DIR / "assets" / "images"
    for d in (css_dir, js_dir, icons_dir, images_dir):
        d.mkdir(parents=True)

    for name in CSS_FILES:
        copy_file(PROTO / "styles" / name, css_dir / name)

    favicon = PROTO / "favicon.svg"
    copy_file(favicon, icons_dir / "favicon.svg")
    copy_file(favicon, images_dir / "eco-dms-logo.svg")

    contract_json = json.loads((PROTO / "data" / "contract.json").read_text(encoding="utf-8"))
    seed_js = (
        "window.__CONTRACT_SEED = "
        + json.dumps(contract_json, ensure_ascii=False, indent=2)
        + ";\n"
        "window.__contractStore = JSON.parse(JSON.stringify(window.__CONTRACT_SEED));\n"
        "window.__CONTRACT_MENU_ITEMS = "
        + json.dumps(MENU_ITEMS, ensure_ascii=False, indent=2)
        + ";\n"
    )
    write_text(js_dir / "contract-data.js", seed_js)

    copy_file(PROTO / "scripts" / "component-core.js", js_dir / "component-core.js")
    copy_file(PROTO / "layouts" / "main-layout.js", js_dir / "main-layout.js")
    patch_contract_shared(PROTO / "scripts" / "contract-shared.js", js_dir / "contract-shared.js")
    copy_file(PROTO / "pages" / "contract" / "page.js", js_dir / "contract-page.js")
    patch_router_default(PROTO / "router" / "router.js", js_dir / "router.js")
    write_text(js_dir / "app.js", APP_JS)

    script_tags = [
        "assets/js/contract-data.js",
        "assets/js/component-core.js",
        "assets/js/main-layout.js",
    ]
    for name in COMPONENTS:
        src = PROTO / "components" / name / "script.js"
        dest = js_dir / "components" / f"{name}.js"
        copy_file(src, dest)
        script_tags.append(f"assets/js/components/{name}.js")

    script_tags.extend([
        "assets/js/contract-shared.js",
        "assets/js/contract-page.js",
        "assets/js/router.js",
        "assets/js/app.js",
    ])

    write_text(OUT_DIR / "index.html", build_index_html(script_tags))
    write_text(OUT_DIR / "README.md", README)

    zip_dir(OUT_DIR, ZIP_PATH)

    files = [p for p in OUT_DIR.rglob("*") if p.is_file()]
    print(f"Exported {len(files)} files -> {OUT_DIR}")
    print(f"ZIP -> {ZIP_PATH} ({ZIP_PATH.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
