import type { Contact } from './types';

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: '1',
    contactId: 'CON_001',
    role: 'Mua hàng',
    salutation: 'Mr.',
    lastName: 'Nguyễn',
    middleName: 'Văn',
    firstName: 'A',
    jobTitle: 'Purchasing Lead',
    category: 'VIP',
    email: 'vana@finviet.vn',
    mainPhone: '0987654321',
    fax: '028-3925-1111',
    leadSource: 'Website',
    comments: '',
    addresses: [
      {
        id: '1-1',
        label: 'Finviet HQ',
        types: ['billing', 'shipping'],
        country: 'Vietnam',
        attention: 'Phòng mua hàng',
        addressee: 'Nguyễn Văn A',
        phone: '0987654321',
        addressLine1: '123 Trần Hưng Đạo',
        city: 'TP. Hồ Chí Minh',
        ward: 'Bến Nghé',
        zipCode: '700000',
        latitude: '10.762622',
        longitude: '106.682215',
      },
    ],
    status: 'Active',
    linkedCustomerCount: 1,
    source: 'DMS',
  },
  {
    id: '2',
    contactId: 'CON_002',
    role: 'Chủ doanh nghiệp',
    salutation: 'Mrs.',
    lastName: 'Trần',
    middleName: 'Thị',
    firstName: 'B',
    jobTitle: 'CEO',
    category: 'Thân thiết',
    email: 'thib@vigo.vn',
    mainPhone: '0912345678',
    fax: '024-3855-2222',
    leadSource: 'Facebook',
    comments: 'Khách hàng thân thiết, ưu tiên chăm sóc.',
    addresses: [
      {
        id: '2-1',
        label: 'VIGO Office',
        types: ['shipping'],
        country: 'Vietnam',
        attention: 'Ban Giám đốc',
        addressee: 'Trần Thị B',
        phone: '0912345678',
        addressLine1: '456 Lê Duẩn',
        city: 'Hà Nội',
        ward: 'Đống Đa',
        zipCode: '100000',
        latitude: '21.028511',
        longitude: '105.804817',
      },
    ],
    status: 'Active',
    linkedCustomerCount: 3,
    source: 'ERP',
  },
  {
    id: '3',
    contactId: 'CON_003',
    role: 'Người nhận hàng',
    salutation: 'Mr.',
    lastName: 'Phạm',
    middleName: 'Minh',
    firstName: 'C',
    jobTitle: 'Logistics Staff',
    category: 'Mới',
    email: 'minhc@unilever.com',
    mainPhone: '0909999888',
    fax: '',
    leadSource: 'Partner Referral',
    comments: '',
    addresses: [
      {
        id: '3-1',
        label: 'Kho Unilever Củ Chi',
        types: [],
        country: 'Vietnam',
        attention: 'Kho số 3',
        addressee: 'Phạm Minh C',
        phone: '0909999888',
        addressLine1: 'Đường số 2, KCN Tây Bắc Củ Chi',
        city: 'TP. Hồ Chí Minh',
        ward: 'Thủ Đức',
        zipCode: '730000',
        latitude: '10.982133',
        longitude: '106.495811',
      },
    ],
    status: 'Inactive',
    linkedCustomerCount: 0,
    source: 'DMS',
  },
  {
    id: '4',
    contactId: 'CON_004',
    role: 'Quản lý',
    salutation: 'Mr.',
    lastName: 'Lê',
    middleName: 'Hoàng',
    firstName: 'D',
    jobTitle: 'Regional Sales Manager',
    category: 'Tiềm năng',
    email: 'hoangd@masan.vn',
    mainPhone: '0945666777',
    fax: '028-3822-3333',
    leadSource: 'Event',
    comments: '',
    addresses: [
      {
        id: '4-1',
        label: 'Masan Plaza',
        types: ['billing'],
        country: 'Vietnam',
        attention: 'Bộ phận Kinh doanh',
        addressee: 'Lê Hoàng D',
        phone: '0945666777',
        addressLine1: '235 Nguyễn Văn Cừ',
        city: 'TP. Hồ Chí Minh',
        ward: 'An Phú',
        zipCode: '740000',
        latitude: '10.759902',
        longitude: '106.677843',
      },
    ],
    status: 'Active',
    linkedCustomerCount: 2,
    source: 'DMS',
  },
];
